POST http://localhost:3000/jwtDecode
# x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NDU0MTQ5MTIsImV4cCI6MTY0NTUwMTMxMn0.wUZ_EVpj7rkSZiL0DFTz-Yae-F1uXudhlTGpqQ2o3UI
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NDU0MTQ5MTIsImV4cCI6MTY0NTUwMTMxMn0.wUZ_EVpj7rkSZiL0DFTz-Yae-F1uXudhlTGpqQ2o3UI